/**
 * Dual Keypair Helper for Playwright Tests
 *
 * Generates Ed25519 + X25519 keypairs for dual-key system tests (Sistema A)
 * Uses existing generate_dual_keypairs.js script for consistency with bash tests
 *
 * IMPORTANT: Sistema A (temporary session keys for frontend-backend communication)
 * Both Ed25519 and X25519 keys are generated together and must be used together.
 * The Ed25519 private key is used to sign SignedRequest, and the public key
 * is included in the payload for backend verification.
 */

import { execSync } from 'child_process';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ES module equivalent of __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface DualKeypairs {
	ed25519_pub_key: string;
	x25519_pub_key: string;
}

/**
 * Generate dual keypairs (Ed25519 + X25519) using Node.js script
 *
 * This ensures consistency with bash tests and backend expectations.
 * Private keys are stored in .test-ed25519-private-key and .test-x25519-private-key
 * in the web/ directory (cwd of execution).
 *
 * @returns Dual public keys in hex format (64 chars each)
 */
export function generateDualKeypairs(): DualKeypairs {
	const scriptsDir = path.resolve(__dirname, '../../../scripts');
	const scriptPath = path.join(scriptsDir, 'generate_dual_keypairs.js');

	try {
		const output = execSync(`node "${scriptPath}"`, {
			encoding: 'utf-8',
			cwd: path.resolve(__dirname, '../..')
		});

		return JSON.parse(output) as DualKeypairs;
	} catch (error) {
		throw new Error(`Failed to generate dual keypairs: ${error}`);
	}
}

/**
 * Read Ed25519 private key from file (generated by generateDualKeypairs)
 *
 * This private key is used to sign SignedRequest and must match the
 * ed25519_pub_key in the payload.
 *
 * @returns Ed25519 private key in hex format (64 chars)
 */
export function readEd25519PrivateKey(): string {
	const keyPath = path.resolve(__dirname, '../../.test-ed25519-private-key');

	try {
		return readFileSync(keyPath, 'utf-8').trim();
	} catch (error) {
		throw new Error(`Failed to read Ed25519 private key from ${keyPath}: ${error}`);
	}
}

/**
 * Create magic link payload with dual-key format
 *
 * @param email - User email
 * @param dualKeypairs - Generated dual keypairs
 * @param next - Optional redirect path (default: '/')
 * @returns Payload object ready for SignedRequest
 */
export function createMagicLinkPayload(
	email: string,
	dualKeypairs: DualKeypairs,
	next: string = '/'
): object {
	return {
		email,
		email_lang: 'en',
		next,
		ed25519_pub_key: dualKeypairs.ed25519_pub_key,
		x25519_pub_key: dualKeypairs.x25519_pub_key,
		ui_host: 'localhost'
	};
}
