spin_manifest_version = 2

[application]
name = "hashrand-spin"
version = "0.1.0"
authors = ["Arkaitz Dev <me@arkaitz.dev>"]
description = "A random hash generator API built with Fermyon Spin"

[[trigger.http]]
route = "/api/..."
component = "hashrand-spin"

[component.hashrand-spin]
source = "target/wasm32-wasip1/release/hashrand_spin.wasm"
allowed_outbound_hosts = []
[component.hashrand-spin.build]
command = "cargo build --target wasm32-wasip1 --release --manifest-path api/Cargo.toml"
watch = ["api/src/**/*.rs", "api/Cargo.toml"]
